### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Qhilm** [schwark/alfred-simplelogin#3]
I just installed the workflow and I got this error after `sl update`.

Then I uninstalled and reinstalled the workflow and now I get this immediately, I can't even configure the API key.

macOS 14.3.1
Alfred 5.1.4
SL workflow 0.0.4 (package, didn't compile it myself)

```
09:06:21 filter.py:198 DEBUG    extract_commands: {'query': 'ex'}
09:06:21 workflow.py:2298 ERROR    'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/redacted/Library/CloudStorage/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.287F9A7F-1745-495C-99CE-43266B1CE72E/workflow/workflow.py", line 2292, in run
    func(self)
  File "/Users/redacted/Library/CloudStorage/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.287F9A7F-1745-495C-99CE-43266B1CE72E/filter.py", line 399, in main
    item['list'] = list(filter(lambda x: x, item['list']))
TypeError: 'NoneType' object is not iterable
09:06:21 workflow.py:2322 DEBUG    ---------- finished in 0.038s ----------
[09:06:21.640] SimpleLogin[Script Filter] {
  "items": [
    {
      "title": "Error in workflow 'SimpleLogin'",
      "subtitle": "'NoneType' object is not iterable",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
```

**Comment by schwark** [comment]
Fixed in 0.0.5 - I think

**Comment by Qhilm** [comment]
yep, works, thanks!

Question: does the workflow connect to google.com for some reason?

**Comment by schwark** [comment]
Not that I am aware of
